version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "f003"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1kmt4d3vtxom3"
s3_prefix = "f003"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
